name: bills_control
description: "A new Flutter project."

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  toon: ^0.0.1
  toon_format: ^0.1.0
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  flutter_sizer: ^1.0.5
  excel: ^4.0.6
  open_file: ^3.5.11
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
  